---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: create-frontend-dockerfile
spec:
  description: >-
    Tekton task to create a dockerfile for the frontend builds
  params:
    - default: "source"
      description: directory in the `output` Workspace to clone the repo into.
      name: subdirectory
      type: string
    - name: path-context
      description: path context directory inside the repo
      type: string
    - name: component
      description: name of app-sre application folder this component lives in
      type: string
    - name: image
      description: |
        image should match the quay repo set by app.yaml in app-interface
      type: string
    - name: node-build-version
      description: node version to build the app
      type: string
      default: 16
    - name: quay-expire-time
      description: time for the image to expire in Quay. Default is 3 days
      type: string
      default: 3d
    - name: npm-build-script
      type: string
      description: npm script to run at build time
      default: build
    - name: yarn-build-script
      type: string
      description: yarn script to run at build time
      default: build:prod
    - name: route-path
      type: string
      description: path for the app to be stored
      default: ""
    - name: beta-route-path
      type: string
      description: path for the beta app to be stored
      default: ""
    - name: preview-route-path
      type: string
      description: path for the preview app to be stored
      default: ""
    - name: is-pr
      type: string
      description: true if it comes from a PR
      default: "true"
    - name: ci-root
      type: string
      description: root of the ci.sh script
      default: ""
    - name: server-name
      type: string
      description: name of the server. If empty, same as the app name
      default: ""
    - name: dist-folder
      type: string
      description: directory where the app.info.json will be written
      default: ""
  workspaces:
    - name: source
      description: workspace where the code is stored
  steps:
    - name: create-dockerfile
      image: quay.io/cloudservices/frontend-build-container:latest
      script: |
        #!/usr/bin/env sh
        set -xe

        source_path=$(workspaces.source.path)/$(params.subdirectory)/$(params.path-context)

        cp -r  $source_path/. /workspace
        ls -a /workspace
        sh /container_workspace/universal_build.sh

        cp /container_workspace/Dockerfile $source_path
        cp /container_workspace/Caddyfile $source_path
        cp -r /container_workspace/dist $source_path
      env:
        - name: COMPONENT
          value: $(params.component)
        - name: IMAGE
          value: $(params.image)
        - name: NODE_BUILD_VERSION
          value: $(params.node-build-version)
        - name: QUAY_EXPIRE_TIME
          value: $(params.quay-expire-time)
        - name: NPM_BUILD_SCRIPT
          value: $(params.npm-build-script)
        - name: YARN_BUILD_SCRIPT
          value: $(params.yarn-build-script)
        - name: ROUTE_PATH
          value: $(params.route-path)
        - name: BETA_ROUTE_PATH
          value: $(params.beta-route-path)
        - name: PREVIEW_ROUTE_PATH
          value: $(params.preview-route-path)
        - name: IS_PR
          value: $(params.is-pr)
        - name: CI_ROOT
          value: $(params.ci-root)
        - name: SERVER_NAME
          value: $(params.server-name)
        - name: DIST_FOLDER
          value: $(params.dist-folder)
