name: yamllint-check
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  validate-yaml:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: run yamllint
        run: yamllint ./tasks
